var translations = {
  "site_name": "FCS Consulting",
  "home_title": "Our clients are the essence of what we do",
  "home_sub_title": "We are a consulting agency based in Lisbon, Portugal.",
  "home_sub_text": "Welcome to our vibrant and dynamic consulting firm, where youth and intelligence converge! As a young and agile consultancy, we bring fresh perspectives and innovative ideas to every project we take on. Our team of brilliant minds is dedicated to providing insightful solutions that drive success and growth. Together, we navigate the ever-changing business landscape with creativity, intelligence, and a passion for excellence. Join us on this exciting journey as we unlock new possibilities and shape a brighter future together.",
  "menu_home": "Home",
  "menu_about": "About",
  "menu_services": "Services",
  "menu_blog": "Blog",
  "menu_our_clients": "Our clients",
  "menu_contact": "Contact",
  "title_consultation": "Consultation",
  "home_entre_contato": "Get in touch",
  "menu_navigation": "Navigation",
  "label_contact_country": "Portugal",
  "value_contact_address": "185 5th October Street, Porto, Portugal",
  "value_contact_email": "contact@fcsconsulting.pt",
  "value_contact_phone": "+351 937193405",
  "label_footer_rights": "All rights reserved.",
  "label_contact_info": "Contacts",
  "label_contact_address": "Address",
  "label_contact_phone": "Phone",
  "label_contact_email": "Email",
  "sb_label_contact_info": "Send Message",
  "ph_label_write_your_message": "Write your message.",
  "ph_label_email_address": "Email address",
  "ph_label_last_name": "Last name",
  "ph_label_first_name": "First name",
  "label_en": "English",
  "label_es": "Spanish",
  "label_pt_br": "Portuguese (Brazil)",
  "label_pt_pt": "Portuguese (Portugal)",
  "label_lng_fr":"French",
  "label_our_clients_title": "Our clients",
  "label_our_clients_sub_title": "We value every partnership we've built over the years",
  "label_our_clients_text": "We value every partnership we've built over the years, and the positive impact these collaborations have on our clients is our greatest reward. In our journey as a consultancy, we've had the privilege to work with a wide range of clients representing diverse industries and sectors. From small startups whose innovative ideas inspire us to large multinational companies whose global presence challenges us to deliver international-level solutions, we are proud to have helped drive the success and growth of our business partners.",
  "label_our_clients_text2": "Our dedication to providing insightful, results-driven solutions has been key to establishing strong and lasting relationships with our clients. We believe that each project is an opportunity for mutual growth, where we share knowledge and expertise to achieve set goals. By prioritizing the specific needs of each client, we've built a reputation based on trust, transparency, and excellence. With each new challenge, we renew our commitment to delivering the highest standard of quality, adding real value to the businesses of our esteemed clients. We look forward to new partnerships and the opportunity to tread innovative paths towards success together.",

  "servico_1_title": "Java Development",
  "servico_1_text": "Our highly skilled team offers Java development services to meet your specific needs. From start to finish, we are committed to creating robust and scalable solutions that drive your business to success. With deep knowledge of Java technology, we approach each challenge with agility and precision, delivering products that exceed expectations.",

  "servico_2_title": "Data Mining",
  "servico_2_text": "Explore the power of data with our expertise in Data Mining. Our specialized team uses advanced techniques to discover hidden insights in large datasets, revealing valuable opportunities to optimize your processes and make informed strategic decisions. Let us help you extract the maximum value from your data.",

  "servico_3_title": "Business Intelligence (BI)",
  "servico_3_text": "Leverage your business intelligence with our specialized BI services. We understand that accurate and accessible information is crucial to business success. By using the most advanced tools and technologies, we transform data into interactive dashboards and reports, providing you with a clear and comprehensive view of your performance.",

  "servico_4_title": "ETL (Extract, Transform, Load)",
  "servico_4_text": "Simplify the data integration process with our ETL services. Our experienced team uses proven methodologies to extract data from various sources, transform them into suitable formats, and load them into your target system. This ensures that your data is clean, consistent, and ready for precise analysis and insights.",

  "servico_5_title": "OLAP (Online Analytical Processing)",
  "servico_5_text": "Take advantage of our OLAP expertise for advanced and efficient data analysis. With OLAP, you can explore your data interactively, enabling multidimensional analysis and quickly obtaining answers to your most complex questions. Make informed decisions and drive your business to the next level.",

  "servico_6_title": "Data Warehouse",
  "servico_6_text": "Build a solid foundation for your data strategy with our Data Warehouse services. By creating a centralized environment to store and manage your data, we provide a comprehensive view of your business and eliminate information fragmentation. Benefit from our experience in designing and implementing Data Warehouses to enhance your operations.",
};
