var translations = {
  "name_site": "Consulting",
  "home_title": "We are a consulting agency based in Lisbon, Portugal.",
  "home_sub_text": "Welcome to our vibrant and dynamic consulting company, where youth and intelligence meet! As a young and agile consultancy, we bring fresh perspectives and innovative ideas to every project we undertake. Our team of brilliant minds is dedicated to providing insightful solutions that drive success and growth. Together, we navigate the ever-changing business landscape with creativity, intelligence, and a passion for excellence. Join us on this exciting journey as we unlock new possibilities and shape a brighter future together.",
  "menu_home": "Home",
  "menu_about": "About",
  "menu_services": "Services",
  "menu_blog": "Blog",
  "menu_contact": "Contact",
  "title_consultation": "Consultation",
  "home_entre_contato": "Contact Us",
  "menu_navigation": "Navigation",
  "label_contact_country": "Portugal",
  "value_contact_address": "Rua 5 de outubro 185, Porto, Portugal",
  "value_contact_email": "fjbalbino@gmail.com",
  "value_contact_phone": "+351 937193405",
  "label_footer_rights": "All rights reserved.",
  "label_contact_info": "Contacts",
  "label_contact_address": "Address",
  "label_contact_phone": "Phone",
  "label_contact_email": "Email",
  "sb_label_contact_info": "Send Message",
  "ph_label_write_your_message": "Write your message.",
  "ph_label_email_address": "Email address",
  "ph_label_last_name": "Last name",
  "ph_label_first_name": "First name"
  };