var translations = {
  "site_name": "FCS Consultoría",
  "consulting": "Consultoría",
  "home_title": "Nuestros clientes son la esencia de lo que hacemos",
  "home_sub_title": "Somos una agencia de consultoría con sede en Lisboa, Portugal.",
  "home_sub_text": "¡Bienvenido a nuestra vibrante y dinámica empresa de consultoría, donde la juventud y la inteligencia se encuentran! Como una consultoría joven y ágil, aportamos perspectivas frescas e ideas innovadoras a cada proyecto que asumimos. Nuestro equipo de mentes brillantes está dedicado a proporcionar soluciones perspicaces que impulsan el éxito y el crecimiento. Juntos, navegamos por el cambiante paisaje empresarial con creatividad, inteligencia y pasión por la excelencia. Únete a nosotros en este emocionante viaje mientras desbloqueamos nuevas posibilidades y moldeamos juntos un futuro más brillante.",
  "menu_home": "Principal",
  "menu_about": "Acerca de",
  "menu_services": "Servicios",
  "menu_blog": "Blog",
  "menu_our_clients": "Nuestros clientes",
  "menu_contact": "Contacto",
  "title_consultation": "Consulta",
  "home_entre_contato":"Contacta con nosotros",
  "menu_navigation":"Navegación",
  "label_contact_country":"Portugal",
  "value_contact_address":"Rua 5 de outubro 185, Oporto, Portugal",
  "value_contact_email":"contacto@fcsconsulting.pt",
  "value_contact_phone":"+351 937193405",
  "label_footer_rights":"Todos los derechos reservados.",
  "label_contact_info":"Contactos",
  "label_contact_address":"Dirección",
  "label_contact_phone":"Teléfono",
  "label_contact_email":"Correo electrónico",
  "sb_label_contact_info":"Enviar Mensaje",
  "ph_label_write_your_message":"Escribe tu mensaje.",
  "ph_label_email_address":"Dirección de correo electrónico",
  "ph_label_last_name":"Apellido",
  "ph_label_first_name":"Nombre",
  "label_en":"Inglés",
  "label_es":"Español",
  "label_pt_br":"PT-BR",
  "label_pt_pt":"PT-PT",
  "label_lng_fr":"Francés",
  "label_our_clients_title":"Nuestros clientes",
  "label_our_clients_sub_title":"Valoramos cada colaboración que hemos construido a lo largo de los años",
  "label_our_clients_text":"Valoramos cada colaboración que hemos construido a lo largo de los años, y el impacto positivo que estas colaboraciones tienen en nuestros clientes es nuestra mayor recompensa. En nuestro camino como consultoría, hemos tenido el privilegio de trabajar con una amplia gama de clientes que representan diversas industrias y sectores. Desde pequeñas startups, cuyas ideas innovadoras nos inspiran, hasta grandes empresas multinacionales, cuya presencia global nos desafía a ofrecer soluciones de nivel internacional, estamos orgullosos de haber contribuido al éxito y al crecimiento de nuestros socios comerciales.",
  "label_our_clients_text2":"Nuestra dedicación para proporcionar soluciones perspicaces y orientadas a resultados ha sido clave para establecer relaciones sólidas y duraderas con nuestros clientes. Creemos que cada proyecto es una oportunidad de crecimiento mutuo, donde compartimos conocimientos y experiencia para alcanzar los objetivos establecidos. Al priorizar las necesidades específicas de cada cliente, hemos construido una reputación basada en confianza, transparencia y excelencia. Con cada nuevo desafío, renovamos nuestro compromiso para ofrecer el más alto estándar de calidad, agregando un valor real a los negocios de nuestros estimados clientes. Esperamos con ansias nuevas colaboraciones y la oportunidad de recorrer caminos innovadores hacia el éxito juntos.",

  "servico_1_title": "Desarrollo Java",
  "servico_1_text": "Nuestro equipo altamente calificado ofrece servicios de desarrollo en Java para satisfacer tus necesidades específicas. Desde el inicio hasta el final, estamos comprometidos a crear soluciones robustas y escalables que impulsen el éxito de tu empresa. Con un profundo conocimiento en tecnología Java, abordamos cada desafío con agilidad y precisión, entregando productos que superan las expectativas.",

  "servico_2_title": "Minería de Datos",
  "servico_2_text": "Explora el poder de los datos con nuestra experiencia en Minería de Datos. Nuestro equipo especializado utiliza técnicas avanzadas para descubrir conocimientos ocultos en grandes conjuntos de datos, revelando oportunidades valiosas para optimizar tus procesos y tomar decisiones estratégicas fundamentadas. Permítenos ayudarte a extraer el máximo valor de tus datos.",

  "servico_3_title": "Inteligencia de Negocios (BI)",
  "servico_3_text": "Potencia tu inteligencia empresarial con nuestros servicios especializados en BI. Comprendemos que la información precisa y accesible es crucial para el éxito de los negocios. Utilizando las herramientas y tecnologías más avanzadas, transformamos datos en paneles de control e informes interactivos, proporcionándote una visión clara y completa de tu rendimiento.",

  "servico_4_title": "ETL (Extracción, Transformación y Carga)",
  "servico_4_text": "Simplifica el proceso de integración de datos con nuestros servicios ETL. Nuestro experimentado equipo utiliza metodologías comprobadas para extraer datos de diversas fuentes, transformarlos en formatos adecuados y cargarlos en tu sistema de destino. Esto garantiza que tus datos estén limpios, consistentes y listos para ser utilizados en análisis e información precisa.",

  "servico_5_title": "Procesamiento Analítico en Línea (OLAP)",
  "servico_5_text": "Aprovecha nuestra experiencia en OLAP para un análisis de datos avanzado y eficiente. Con OLAP, podrás explorar tus datos de manera interactiva, permitiendo análisis multidimensionales y la rápida obtención de respuestas para tus preguntas más complejas. Toma decisiones informadas y lleva tu empresa al siguiente nivel.",

  "servico_6_title": "Almacén de Datos (Data Warehouse)",
  "servico_6_text": "Construimos una sólida base para tu estrategia de datos con nuestros servicios de Data Warehouse. Al crear un entorno centralizado para almacenar y gestionar tus datos, proporcionamos una visión integral de tu negocio y eliminamos la fragmentación de la información. Aprovecha nuestra experiencia en diseño e implementación de Data Warehouses para mejorar tus operaciones.",

  "servico_7_title": "Desarrollo .NET",
  "servico_7_text": "Dentro de nuestra oferta de desarrollo, también abarcamos la plataforma .NET, brindando soluciones personalizadas para satisfacer sus demandas específicas. Nuestro equipo altamente calificado tiene la capacidad de aprovechar todo el potencial del entorno .NET, garantizando el desarrollo de aplicaciones robustas, escalables y de alto rendimiento. Desde el diseño hasta la implementación, estamos comprometidos con entregar productos que agreguen valor e impulsen su eficiencia operativa.",
  
  "servico_8_title": "BIG DATA",
  "servico_8_text": "Aproveche nuestra experiencia en Big Data para extraer el potencial máximo de sus datos. Nuestro equipo especializado está listo para manejar conjuntos de datos masivos y complejos, utilizando técnicas avanzadas para el procesamiento, análisis e interpretación. Descubra patrones, tendencias e información oculta que pueden revolucionar su toma de decisiones e impulsar su ventaja competitiva en el mercado.",
  
  "servico_9_title": "Gestión de Proyectos Ágiles",
  "servico_9_text": "Nuestro experimentado equipo en gestión de proyectos ágiles está listo para colaborar en el éxito de sus emprendimientos. Utilizando enfoques ágiles probados, como Scrum y Kanban, facilitamos la entrega eficiente de proyectos complejos. Mediante iteraciones regulares y retroalimentación continua, aseguramos la adaptación a los cambios y prioridades, lo que resulta en la entrega puntual de soluciones de alta calidad que satisfacen sus necesidades en constante evolución."
};
