var translations = {
  "name_site": "Consultoria",
  "home_title": "Somos uma agência de consultoria sediada em Lisboa, Portugal.",
  "home_sub_text": "Bem-vindo à nossa vibrante e dinâmica empresa de consultoria, onde juventude e inteligência se encontram! Como uma consultoria jovem e ágil, trazemos perspectivas frescas e ideias inovadoras para cada projeto que assumimos. Nossa equipe de mentes brilhantes está dedicada a fornecer soluções perspicazes que impulsionam o sucesso e o crescimento. Juntos, navegamos pela paisagem empresarial em constante evolução com criatividade, inteligência e uma paixão pela excelência. Junte-se a nós nessa jornada emocionante enquanto desbloqueamos novas possibilidades e moldamos um futuro mais brilhante juntos.",
  "menu_home": "Principal",
  "menu_about": "Sobre",
  "menu_services": "Serviços",
  "menu_blog": "Blog",
  "menu_contact": "Contato",
  "title_consultation": "Consulta",
  "home_entre_contato":"Entre em contato",
  "menu_navigation":"Navegação",
  "label_contact_country":"Portugal",
  "value_contact_address":"Rua 5 de outubro 185, Porto, Portugal",
  "value_contact_email":"hello@mydomain.com",
  "value_contact_phone":"+351 937193405",
  "label_footer_rights":"Todos os direitos reservados.",
  "label_contact_info":"Contatos",
  "label_contact_address":"Endereço",
  "label_contact_phone":"Telefone",
  "label_contact_email":"E-mail",
  "sb_label_contact_info":"Enviar Mensagem",
  "ph_label_write_your_message":"Escreva sua mensagem.",
  "ph_label_email_address":"Endereço de e-mail",
  "ph_label_last_name":"Último nome",
  "ph_label_first_name":"Primeiro nome"
};