var translations = {
  "site_name": "FCS Conseil",
  "home_title": "Nos clients sont l'essence de ce que nous faisons",
  "home_sub_title": "Nous sommes une agence de conseil basée à Lisbonne, Portugal.",
  "home_sub_text": "Bienvenue dans notre entreprise de conseil vibrante et dynamique, où jeunesse et intelligence se rencontrent ! En tant que cabinet de conseil jeune et agile, nous apportons des perspectives fraîches et des idées novatrices à chaque projet que nous entreprenons. Notre équipe de brillantes intelligences est dédiée à fournir des solutions perspicaces qui favorisent le succès et la croissance. Ensemble, nous naviguons dans le paysage commercial en constante évolution avec créativité, intelligence et passion pour l'excellence. Rejoignez-nous dans cette aventure passionnante alors que nous débloquons de nouvelles possibilités et façonnons ensemble un avenir plus brillant.",
  "menu_home": "Accueil",
  "menu_about": "À propos",
  "menu_services": "Services",
  "menu_blog": "Blog",
  "menu_our_clients": "Nos clients",
  "menu_contact": "Contact",
  "title_consultation": "Consultation",
  "home_entre_contato":"Prenez contact",
  "menu_navigation":"Navigation",
  "label_contact_country":"Portugal",
  "value_contact_address":"Rua 5 de outubro 185, Porto, Portugal",
  "value_contact_email":"contact@fcsconsulting.pt",
  "value_contact_phone":"+351 937193405",
  "label_footer_rights":"Tous droits réservés.",
  "label_contact_info":"Contacts",
  "label_contact_address":"Adresse",
  "label_contact_phone":"Téléphone",
  "label_contact_email":"E-mail",
  "sb_label_contact_info":"Envoyer un message",
  "ph_label_write_your_message":"Écrivez votre message.",
  "ph_label_email_address":"Adresse e-mail",
  "ph_label_last_name":"Nom de famille",
  "ph_label_first_name":"Prénom",
  "label_en":"Anglais",
  "label_es":"Espagnol",
  "label_pt_br":"PT-BR",
  "label_pt_pt":"PT-PT",
  "label_lng_fr":"Français",
  "label_our_clients_title":"Nos clients",
  "label_our_clients_sub_title":"Nous valorisons chaque partenariat que nous construisons au fil des ans",
  "label_our_clients_text":"Nous valorisons chaque partenariat que nous construisons au fil des ans et l'impact positif que ces collaborations ont sur nos clients est notre plus grande récompense. Dans notre parcours en tant que cabinet de conseil, nous avons eu le privilège de travailler avec un large éventail de clients représentant diverses industries et secteurs. Des petites start-ups, dont les idées novatrices nous inspirent, aux grandes entreprises multinationales, dont la présence mondiale nous pousse à fournir des solutions de niveau international, nous sommes fiers d'avoir contribué à stimuler le succès et la croissance de nos partenaires commerciaux.",
  "label_our_clients_text2":"Notre dévouement à fournir des solutions perspicaces et axées sur les résultats a été la clé pour établir des relations solides et durables avec nos clients. Nous croyons que chaque projet est une opportunité de croissance mutuelle, où nous partageons connaissances et expertise pour atteindre les objectifs fixés. En priorisant les besoins spécifiques de chaque client, nous avons bâti une réputation basée sur la confiance, la transparence et l'excellence. Avec chaque nouveau défi, nous renouvelons notre engagement à offrir le plus haut niveau de qualité, en ajoutant une valeur réelle aux entreprises de nos estimés clients. Nous sommes impatients de nouvelles collaborations et de l'occasion de parcourir ensemble des chemins innovants vers le succès.",
  
  "servico_1_title": "Développement Java",
  "servico_1_text": "Notre équipe hautement qualifiée propose des services de développement en Java pour répondre à vos besoins spécifiques. Du début à la fin, nous nous engageons à créer des solutions robustes et évolutives qui propulsent votre entreprise vers le succès. Forts de notre profonde connaissance de la technologie Java, nous abordons chaque défi avec agilité et précision, en livrant des produits qui dépassent les attentes.",

  "servico_2_title": "Data Mining (Exploration de données)",
  "servico_2_text": "Explorez la puissance des données avec notre expertise en Data Mining. Notre équipe spécialisée utilise des techniques avancées pour découvrir des informations cachées dans de grands ensembles de données, révélant ainsi des opportunités précieuses pour optimiser vos processus et prendre des décisions stratégiques éclairées. Laissez-nous vous aider à tirer le maximum de valeur de vos données.",

  "servico_3_title": "Business Intelligence (BI)",
  "servico_3_text": "Optimisez votre intelligence d'entreprise avec nos services spécialisés en BI. Nous comprenons que des informations précises et accessibles sont cruciales pour le succès des entreprises. En utilisant les outils et technologies les plus avancés, nous transformons les données en tableaux de bord et rapports interactifs, vous offrant une vision claire et globale de votre performance.",

  "servico_4_title": "ETL (Extraction, Transformation, Chargement)",
  "servico_4_text": "Simplifiez le processus d'intégration de données avec nos services ETL. Notre équipe expérimentée utilise des méthodologies éprouvées pour extraire des données de différentes sources, les transformer en formats adaptés et les charger dans votre système cible. Cela garantit que vos données sont propres, cohérentes et prêtes à être utilisées pour des analyses et des insights précis.",

  "servico_5_title": "OLAP (Traitement analytique en ligne)",
  "servico_5_text": "Profitez de notre expertise en OLAP pour une analyse avancée et efficace des données. Avec l'OLAP, vous pourrez explorer vos données de manière interactive, permettant des analyses multidimensionnelles et l'obtention rapide de réponses à vos questions les plus complexes. Prenez des décisions éclairées et propulsez votre entreprise vers le niveau supérieur.",

  "servico_6_title": "Data Warehouse (Entrepôt de données)",
  "servico_6_text": "Nous construisons une base solide pour votre stratégie de données avec nos services de Data Warehouse. En créant un environnement centralisé pour stocker et gérer vos données, nous vous offrons une vision globale de votre entreprise et éliminons la fragmentation des informations. Profitez de notre expertise en conception et mise en œuvre de Data Warehouses pour améliorer vos opérations.",
};
